export type ExpenseCategory =
  | 'Food & Dining'
  | 'Transport'
  | 'Utilities & Bills'
  | 'Shopping'
  | 'Health'
  | 'Entertainment'
  | 'Education'
  | 'Custom'

export type AssetCategory =
  | 'Cash / Bank'
  | 'Real estate'
  | 'Stocks'
  | 'Mutual funds'
  | 'Gold / Jewelry'
  | 'Tangible assets'
  | 'Credit card'
  | 'Liability'

export type InvestmentType =
  | 'Stocks'
  | 'Crypto'
  | 'Bonds'
  | 'Other'

export type MutualFundType =
  | 'Money Market'
  | 'Equity'
  | 'Income'
  | 'Balanced'
  | 'Index'
  | 'Islamic'
  | 'Other'

export interface MutualFund {
  id: string
  name: string
  fundType: MutualFundType
  unitsHeld: number
  buyNav: number          // PKR per unit at purchase
  currentNav: number      // PKR per unit now (manually overridable)
  navOverride: number | null  // manual fallback if fetch fails
  lastUpdated: string | null  // ISO date of last NAV update
  realizedGains: number   // from units already sold
  notes: string
}

export const MUTUAL_FUND_TYPES: MutualFundType[] = [
  'Money Market',
  'Equity',
  'Income',
  'Balanced',
  'Index',
  'Islamic',
  'Other',
]

export interface Expense {
  id: string
  description: string
  amount: number
  category: ExpenseCategory
  date: string
  receiptUrl?: string
  account?: string // e.g. a bank account name, or "Cash"
}

export type BankAccountType = 'Checking' | 'Saving' | 'Credit Card'

export const BANK_ACCOUNT_TYPES: BankAccountType[] = ['Checking', 'Saving', 'Credit Card']

export const PAKISTANI_BANKS: string[] = [
  'Allied Bank',
  'Askari Bank',
  'Bank Al Habib',
  'Bank Alfalah',
  'Bank of Khyber',
  'Bank of Punjab',
  'BankIslami Pakistan',
  'Dubai Islamic Bank Pakistan',
  'Faysal Bank',
  'Habib Bank Limited (HBL)',
  'Habib Metropolitan Bank',
  'JS Bank',
  'MCB Bank',
  'Meezan Bank',
  'National Bank of Pakistan',
  'Samba Bank',
  'Silk Bank',
  'Sindh Bank',
  'Soneri Bank',
  'Standard Chartered Pakistan',
  'Summit Bank',
  'United Bank Limited (UBL)',
  'Other',
]

export interface BankAccount {
  id: string
  bank: string
  nickname: string
  type: BankAccountType
  startingBalance: number
  dueDate?: string // Credit Card only — ISO date of next payment due
}

// Loaded data from before this field set existed may be missing fields —
// fall back gracefully rather than crash on legacy records.
export function bankAccountLabel(b: Partial<BankAccount>): string {
  const nickname = (b.nickname ?? '').trim()
  if (nickname) return nickname
  if (b.bank) return b.type ? `${b.bank} — ${b.type}` : b.bank
  return 'Account'
}

export interface NetWorthSnapshot {
  date: string
  value: number
}

export type IncomeFrequency = 'Weekly' | 'Bi-weekly' | 'Monthly' | 'Quarterly' | 'Yearly'

export const INCOME_FREQUENCIES: IncomeFrequency[] = [
  'Weekly',
  'Bi-weekly',
  'Monthly',
  'Quarterly',
  'Yearly',
]

export type IncomeCategory =
  | 'Salary'
  | 'Business Income'
  | 'Freelance / Remote Work'
  | 'Rental Income'
  | 'Foreign Remittance'
  | 'Bank Profit'
  | 'Dividends'
  | 'Capital Gains'
  | 'Agricultural Income'
  | 'Pension'
  | 'Bonus / Commission'
  | 'Provident Fund / Gratuity'
  | 'Prize Bond Winnings'
  | 'Other'

export const INCOME_CATEGORIES: IncomeCategory[] = [
  'Salary',
  'Business Income',
  'Freelance / Remote Work',
  'Rental Income',
  'Foreign Remittance',
  'Bank Profit',
  'Dividends',
  'Capital Gains',
  'Agricultural Income',
  'Pension',
  'Bonus / Commission',
  'Provident Fund / Gratuity',
  'Prize Bond Winnings',
  'Other',
]

export const INCOME_CATEGORY_COLORS: Record<IncomeCategory, string> = {
  'Salary':                     '#2a78d6',
  'Business Income':            '#1baf7a',
  'Freelance / Remote Work':    '#17a2b8',
  'Rental Income':              '#6f42c1',
  'Foreign Remittance':         '#20c997',
  'Bank Profit':                '#0d6efd',
  'Dividends':                  '#6610f2',
  'Capital Gains':              '#d63384',
  'Agricultural Income':        '#558b2f',
  'Pension':                    '#795548',
  'Bonus / Commission':         '#eda100',
  'Provident Fund / Gratuity':  '#8d6e63',
  'Prize Bond Winnings':        '#fd7e14',
  'Other':                      '#73726c',
}

export interface RecurringIncome {
  id: string
  source: string
  category: IncomeCategory
  amount: number
  account: string // e.g. a bank account name, or "Cash"
  frequency: IncomeFrequency
  nextDate: string // ISO date of the next auto-generated entry
}

export interface Income {
  id: string
  source: string
  category: IncomeCategory
  amount: number
  account: string
  date: string
  recurringId?: string // set when this entry was auto-generated by a RecurringIncome
  // Set when a recurring deposit was matched to a real BankAccount and its
  // balance was bumped by this amount — computeNetWorth excludes income with
  // this set from netSavings, since it's already reflected in the account
  // balance instead. Unset (undefined) means it's still counted via netSavings,
  // same as before this field existed.
  depositedToAccountId?: string
}

export interface Asset {
  id: string
  name: string
  value: number
  category: AssetCategory
  // Credit card only
  creditLimit?: number
  dueDate?: string        // ISO date of next payment due
  minimumPayment?: number
}

export const LIABILITY_CATEGORIES: AssetCategory[] = ['Liability', 'Credit card']

export function isLiabilityCategory(category: AssetCategory): boolean {
  return LIABILITY_CATEGORIES.includes(category)
}

export interface Investment {
  id: string
  name: string
  type: InvestmentType
  amountInvested: number
  currentValue: number
  // Stocks only — when a PSX symbol + share count is set, currentValue is
  // kept in sync with the live/last-traded price instead of entered by hand.
  symbol?: string
  sharesHeld?: number
  buyPrice?: number // PKR per share at purchase — amountInvested is sharesHeld * buyPrice
  priceOverride?: number | null
  lastPriceUpdate?: string | null
}

export interface PsxSymbol {
  symbol: string
  name: string
  sectorName: string
}

export type Budgets = Record<ExpenseCategory, number>

export type CurrencyCode = 'PKR' | 'USD' | 'EUR' | 'GBP' | 'AED' | 'SAR'

export const CURRENCIES: { code: CurrencyCode; symbol: string; label: string }[] = [
  { code: 'PKR', symbol: 'Rs',  label: 'Pakistani Rupee (PKR)' },
  { code: 'USD', symbol: '$',   label: 'US Dollar (USD)' },
  { code: 'EUR', symbol: '€',   label: 'Euro (EUR)' },
  { code: 'GBP', symbol: '£',   label: 'British Pound (GBP)' },
  { code: 'AED', symbol: 'AED', label: 'UAE Dirham (AED)' },
  { code: 'SAR', symbol: 'SAR', label: 'Saudi Riyal (SAR)' },
]

export type StockMarketCode = 'PK' | 'US' | 'UK' | 'IN'

// `available` reflects real, wired-up data coverage — only PSX (Pakistan)
// has a live price source (see app/api/psx/*) as of this writing. The
// others are listed so the preference exists ahead of that work landing,
// not hidden behind a fake "coming soon" that looks broken if selected.
export const STOCK_MARKETS: { code: StockMarketCode; label: string; available: boolean }[] = [
  { code: 'PK', label: 'Pakistan — PSX', available: true },
  { code: 'US', label: 'United States — NYSE / NASDAQ', available: false },
  { code: 'UK', label: 'United Kingdom — LSE', available: false },
  { code: 'IN', label: 'India — NSE / BSE', available: false },
]

export interface Preferences {
  currency: CurrencyCode
  stockMarket: StockMarketCode
}

export const DEFAULT_PREFERENCES: Preferences = {
  currency: 'PKR',
  stockMarket: 'PK',
}

export interface AppState {
  expenses: Expense[]
  assets: Asset[]
  investments: Investment[]
  mutualFunds: MutualFund[]
  budgets: Budgets
  incomes: Income[]
  recurringIncomes: RecurringIncome[]
  bankAccounts: BankAccount[]
  netWorthHistory: NetWorthSnapshot[]
  preferences: Preferences
}

export const EXPENSE_CATEGORIES: ExpenseCategory[] = [
  'Food & Dining',
  'Transport',
  'Utilities & Bills',
  'Shopping',
  'Health',
  'Entertainment',
  'Education',
  'Custom',
]

export const ASSET_CATEGORIES: AssetCategory[] = [
  'Cash / Bank',
  'Real estate',
  'Stocks',
  'Mutual funds',
  'Gold / Jewelry',
  'Tangible assets',
  'Credit card',
  'Liability',
]

export const INVESTMENT_TYPES: InvestmentType[] = [
  'Stocks',
  'Crypto',
  'Bonds',
  'Other',
]

export const CATEGORY_COLORS: Record<ExpenseCategory, string> = {
  'Food & Dining':    '#2a78d6',
  'Transport':        '#1baf7a',
  'Utilities & Bills':'#eda100',
  'Shopping':         '#4a3aa7',
  'Health':           '#e34948',
  'Entertainment':    '#e87ba4',
  'Education':        '#eb6834',
  'Custom':           '#73726c',
}

export const ASSET_COLORS: Record<AssetCategory, string> = {
  'Cash / Bank':      '#2a78d6',
  'Real estate':      '#1baf7a',
  'Stocks':           '#4a3aa7',
  'Mutual funds':     '#eda100',
  'Gold / Jewelry':   '#eb6834',
  'Tangible assets':  '#e87ba4',
  'Credit card':      '#c026d3',
  'Liability':        '#e34948',
}

export const INVESTMENT_TYPE_COLORS: Record<InvestmentType, string> = {
  'Stocks': '#2a78d6',
  'Crypto': '#eda100',
  'Bonds':  '#4a3aa7',
  'Other':  '#73726c',
}

export const MUTUAL_FUND_TYPE_COLORS: Record<MutualFundType, string> = {
  'Money Market': '#2a78d6',
  'Equity':       '#1baf7a',
  'Income':       '#eda100',
  'Balanced':     '#4a3aa7',
  'Index':        '#eb6834',
  'Islamic':      '#e87ba4',
  'Other':        '#73726c',
}

export const DEFAULT_BUDGETS: Budgets = {
  'Food & Dining':     50000,
  'Transport':         20000,
  'Utilities & Bills': 30000,
  'Shopping':          25000,
  'Health':            15000,
  'Entertainment':     10000,
  'Education':         20000,
  'Custom':            10000,
}
